# Generated by Django 4.1.5 on 2023-03-27 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_likedposts'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='likedposts',
            table='liked_posts',
        ),
    ]
